x-proxy-settings: &proxy-settings
  HTTP_PROXY: ${HTTP_PROXY:-}
  HTTPS_PROXY: ${HTTPS_PROXY:-}
  NO_PROXY: "localhost,127.0.0.1,mongo,web,.aiiinotate_network"

services:
  mongo:
    image: mongo:8
    restart: always
    networks:
      - aiiinotate_network
    environment:
      <<: *proxy-settings

  aiiinotate:
    build:
      context: ..
      dockerfile: docker/Dockerfile-aiiinotate
      args:
        PORT: ${AIIINOTATE_PORT}
    # NOTE: be careful to point to docker/.env, not to config/.env, otherwise you will have very, very annoying errors.
    env_file:
      - ../docker/.env
    ports:
      - "${AIIINOTATE_PORT}:${AIIINOTATE_PORT}"
    depends_on:
      - mongo
    networks:
      - aiiinotate_network
    environment:
      <<: *proxy-settings
    restart: always

  mirador:
    build:
      context: ..
      dockerfile: docker/Dockerfile-mirador
      args:
        PORT: ${MIRADOR_PORT}
    env_file:
      - ../docker/.env
    depends_on:
      - mongo
      - aiiinotate
    ports:
      - "${MIRADOR_PORT}:${MIRADOR_PORT}"
    networks:
      - aiiinotate_network
    environment:
      <<: *proxy-settings
    restart: always

networks:
  aiiinotate_network:
    driver: bridge